-- MySQL Script generated by MySQL Workbench
-- Mon Sep 22 23:13:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Tipo_Cliente: PF` VARCHAR(45) NULL,
  `Nome:` VARCHAR(45) NULL,
  `Email: Junior.Santos23447@gmail.com` VARCHAR(45) NULL,
  `CNPJ:` VARCHAR(45) NULL,
  `CPF: 376.285.387-21` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_ItemPedido_idItemPedido` INT NOT NULL,
  `Pedido_ItemPedido_Produto_ItemPedido_idItemPedido` INT NOT NULL,
  `Pedido_ItemPedido_Entrega_idEntrega` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Pedido_idPedido`, `Pedido_ItemPedido_idItemPedido`, `Pedido_ItemPedido_Produto_ItemPedido_idItemPedido`, `Pedido_ItemPedido_Entrega_idEntrega`, `Pagamento_idPagamento`),
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_ItemPedido_idItemPedido` ASC, `Pedido_ItemPedido_Produto_ItemPedido_idItemPedido` ASC, `Pedido_ItemPedido_Entrega_idEntrega` ASC) VISIBLE,
  INDEX `fk_Cliente_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_ItemPedido_idItemPedido` , `Pedido_ItemPedido_Produto_ItemPedido_idItemPedido` , `Pedido_ItemPedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `ItemPedido_idItemPedido` , `ItemPedido_Produto_ItemPedido_idItemPedido` , `ItemPedido_Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `id_Pedido` INT NULL,
  `Status_Entrega` VARCHAR(45) NULL,
  `Código_de_Rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemPedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemPedido` (
  `idItemPedido` INT NOT NULL,
  `id_Pedido` VARCHAR(45) NULL,
  `id_Produto` VARCHAR(45) NULL,
  `Quantidade` INT NULL,
  `Preço_Unitário` VARCHAR(45) NULL,
  `Produto_idProduto` INT NOT NULL,
  `Produto_ItemPedido_idItemPedido` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idItemPedido`, `Produto_idProduto`, `Produto_ItemPedido_idItemPedido`, `Entrega_idEntrega`, `Pagamento_idPagamento`, `Pagamento_Cliente_idCliente`),
  INDEX `fk_ItemPedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  INDEX `fk_ItemPedido_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_ItemPedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPedido_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Cliente_idCliente`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `id_Cliente` VARCHAR(45) NULL,
  `Tipo_Pagamento` VARCHAR(45) NULL,
  `Detalhes` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Cliente_idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `id_Cliente` VARCHAR(45) NULL,
  `Data_Pedido` DATE NULL,
  `Valor_Total` DECIMAL(10,2) NULL,
  `ItemPedido_idItemPedido` INT NOT NULL,
  `ItemPedido_Produto_idProduto` INT NOT NULL,
  `ItemPedido_Produto_ItemPedido_idItemPedido` INT NOT NULL,
  `ItemPedido_Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `ItemPedido_idItemPedido`, `ItemPedido_Produto_idProduto`, `ItemPedido_Produto_ItemPedido_idItemPedido`, `ItemPedido_Entrega_idEntrega`),
  INDEX `fk_Pedido_ItemPedido1_idx` (`ItemPedido_idItemPedido` ASC, `ItemPedido_Produto_idProduto` ASC, `ItemPedido_Produto_ItemPedido_idItemPedido` ASC, `ItemPedido_Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_ItemPedido1`
    FOREIGN KEY (`ItemPedido_idItemPedido` , `ItemPedido_Produto_idProduto` , `ItemPedido_Produto_ItemPedido_idItemPedido` , `ItemPedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`ItemPedido` (`idItemPedido` , `Produto_idProduto` , `Produto_ItemPedido_idItemPedido` , `Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Nome_Produto` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Preço` DECIMAL(10,2) NULL,
  `ItemPedido_idItemPedido` INT NOT NULL,
  `ItemPedido_idItemPedido1` INT NOT NULL,
  `ItemPedido_Produto_idProduto` INT NOT NULL,
  `ItemPedido_Produto_ItemPedido_idItemPedido` INT NOT NULL,
  `ItemPedido_Entrega_idEntrega` INT NOT NULL,
  `ItemPedido_Pagamento_idPagamento` INT NOT NULL,
  `ItemPedido_Pagamento_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `ItemPedido_idItemPedido`, `ItemPedido_idItemPedido1`, `ItemPedido_Produto_idProduto`, `ItemPedido_Produto_ItemPedido_idItemPedido`, `ItemPedido_Entrega_idEntrega`, `ItemPedido_Pagamento_idPagamento`, `ItemPedido_Pagamento_Cliente_idCliente`),
  INDEX `fk_Produto_ItemPedido1_idx` (`ItemPedido_idItemPedido1` ASC, `ItemPedido_Produto_idProduto` ASC, `ItemPedido_Produto_ItemPedido_idItemPedido` ASC, `ItemPedido_Entrega_idEntrega` ASC, `ItemPedido_Pagamento_idPagamento` ASC, `ItemPedido_Pagamento_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_ItemPedido1`
    FOREIGN KEY (`ItemPedido_idItemPedido1` , `ItemPedido_Produto_idProduto` , `ItemPedido_Produto_ItemPedido_idItemPedido` , `ItemPedido_Entrega_idEntrega` , `ItemPedido_Pagamento_idPagamento` , `ItemPedido_Pagamento_Cliente_idCliente`)
    REFERENCES `mydb`.`ItemPedido` (`idItemPedido` , `Produto_idProduto` , `Produto_ItemPedido_idItemPedido` , `Entrega_idEntrega` , `Pagamento_idPagamento` , `Pagamento_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
