-- MySQL Script generated by MySQL Workbench
-- Tue Sep 23 22:29:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome: Ronaldo Martins` VARCHAR(100) NULL,
  `Telefone: 71 984732234` VARCHAR(20) NULL,
  `Endereço:` VARCHAR(200) NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Veiculo_idVeiculo`),
  INDEX `fk_Cliente_Veiculo_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Veiculo`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Nome_Equipe: Eq.Falcão` VARCHAR(100) NULL,
  `Ordem de Serviço_id_OS` INT NOT NULL,
  PRIMARY KEY (`idEquipe`, `Ordem de Serviço_id_OS`),
  INDEX `fk_Equipe_Ordem de Serviço1_idx` (`Ordem de Serviço_id_OS` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_id_OS`)
    REFERENCES `mydb`.`Ordem de Serviço` (`id_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_has_Mecânico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe_has_Mecânico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_has_Mecânico` (
  `Equipe_idEquipe` INT NOT NULL,
  `Equipe_Ordem de Serviço_id_OS` INT NOT NULL,
  `Mecânico_idMecânico` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Equipe_Ordem de Serviço_id_OS`, `Mecânico_idMecânico`),
  INDEX `fk_Equipe_has_Mecânico_Mecânico1_idx` (`Mecânico_idMecânico` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Mecânico_Equipe1_idx` (`Equipe_idEquipe` ASC, `Equipe_Ordem de Serviço_id_OS` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Mecânico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe` , `Equipe_Ordem de Serviço_id_OS`)
    REFERENCES `mydb`.`Equipe` (`idEquipe` , `Ordem de Serviço_id_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Mecânico_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecânico`)
    REFERENCES `mydb`.`Mecânico` (`idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecânico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Nome: Cristian Figueras` VARCHAR(100) NULL,
  `Endereço:` VARCHAR(200) NULL,
  `Especialidade: Chassis` VARCHAR(50) NULL,
  PRIMARY KEY (`idMecânico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem de Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `id_OS` INT NOT NULL,
  `Data_Emissão: 05/07/2025` DATE NULL,
  `Data_Conclusão: 08/09/2025` DATE NULL,
  `Valor_Total: 3.576,00` DECIMAL(10,2) NULL,
  `Status: Concluido.` VARCHAR(50) NULL,
  `Autorizada` TINYINT NULL,
  `idVeiculo` INT NULL,
  `idEquipe` INT NULL,
  PRIMARY KEY (`id_OS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço_has_Peças`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem de Serviço_has_Peças` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço_has_Peças` (
  `Ordem de Serviço_id_OS` INT NOT NULL,
  `Peças_idPeças` INT NOT NULL,
  PRIMARY KEY (`Ordem de Serviço_id_OS`, `Peças_idPeças`),
  INDEX `fk_Ordem de Serviço_has_Peças_Peças1_idx` (`Peças_idPeças` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Peças_Ordem de Serviço1_idx` (`Ordem de Serviço_id_OS` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Peças_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_id_OS`)
    REFERENCES `mydb`.`Ordem de Serviço` (`id_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Peças_Peças1`
    FOREIGN KEY (`Peças_idPeças`)
    REFERENCES `mydb`.`Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço_has_Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem de Serviço_has_Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço_has_Serviço` (
  `Ordem de Serviço_id_OS` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  PRIMARY KEY (`Ordem de Serviço_id_OS`, `Serviço_idServiço`),
  INDEX `fk_Ordem de Serviço_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_id_OS` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_id_OS`)
    REFERENCES `mydb`.`Ordem de Serviço` (`id_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Peças` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `idPeças` INT NOT NULL,
  `Nome: Tabareu AUTO-peças` VARCHAR(100) NULL,
  `Valor_unitário` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Descrição` VARCHAR(200) NULL,
  `Valor_Mão_Obra` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Placa: PJX 4M98` VARCHAR(10) NULL,
  `Modelo: Peugeot 208` VARCHAR(50) NULL,
  `Ano: 2014` INT NULL,
  `id_Cliente` INT NULL,
  `Ordem de Serviço_id_OS` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Ordem de Serviço_id_OS`),
  INDEX `fk_Veiculo_Ordem de Serviço1_idx` (`Ordem de Serviço_id_OS` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_id_OS`)
    REFERENCES `mydb`.`Ordem de Serviço` (`id_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
